# Generated by Django 3.2.13 on 2022-05-23 15:47

import article.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150, verbose_name='Название')),
                ('text', models.TextField(default=None, validators=[article.validators.validate_count_words], verbose_name='Текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('upload', sorl.thumbnail.fields.ImageField(default=None, null=True, upload_to='uploads/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('upload', sorl.thumbnail.fields.ImageField(default=None, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='MainArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, validators=[article.validators.validate_count_words], verbose_name='Текст')),
                ('upload', sorl.thumbnail.fields.ImageField(default=None, null=True, upload_to='uploads/')),
                ('articles', models.ManyToManyField(default=None, related_name='main_articles', to='article.Article', verbose_name='Страницы')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to='article.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'главная статья',
                'verbose_name_plural': 'главные статьи',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default='0', max_length=2, verbose_name='Оценка')),
                ('review', models.TextField(max_length=250, verbose_name='Отзыв')),
                ('published_date', models.DateTimeField(verbose_name='Дата отзыва')),
                ('main_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='article.mainarticle', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(null=True, upload_to='uploads/')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='article.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('main_article', 'user'), name='rating_unique'),
        ),
    ]
