# Generated by Django 4.0.3 on 2022-05-22 07:32

import article.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='category',
            name='upload',
            field=sorl.thumbnail.fields.ImageField(default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(default=None, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default=None, validators=[article.validators.validate_count_words], verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='upload',
            field=sorl.thumbnail.fields.ImageField(default=None, null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default='0', max_length=2, verbose_name='Оценка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='article.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='MainArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, validators=[article.validators.validate_count_words], verbose_name='Текст')),
                ('upload', sorl.thumbnail.fields.ImageField(default=None, null=True, upload_to='uploads/')),
                ('articles', models.ManyToManyField(default=None, related_name='main_articles', to='article.article', verbose_name='Страницы')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to='article.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'главная статья',
                'verbose_name_plural': 'главные статьи',
            },
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='rating_unique'),
        ),
    ]
