# Generated by Django 4.0.3 on 2022-05-25 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_mainarticle_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отзыва'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(default=None, max_length=250, null=True, verbose_name='Отзыв'),
        ),
    ]
