# Generated by Django 4.0.3 on 2022-05-23 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_categories_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_unique',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 23), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='rating',
            name='main_article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='article.mainarticle', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=None, verbose_name='Дата отзыва'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(default=None, max_length=250, verbose_name='Отзыв'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('main_article', 'user'), name='rating_unique'),
        ),
    ]
