# Generated by Django 3.2.13 on 2022-05-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_rating_published_date_alter_rating_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainarticle',
            options={'verbose_name': 'вики', 'verbose_name_plural': 'вики'},
        ),
        migrations.AlterField(
            model_name='mainarticle',
            name='articles',
            field=models.ManyToManyField(default=None, related_name='main_articles', to='article.Article', verbose_name='Статьи'),
        ),
        migrations.AlterField(
            model_name='mainarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to='article.category', verbose_name='Категория'),
        ),
    ]
