# Generated by Django 4.0.3 on 2022-05-23 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_rating_rating_unique_remove_rating_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainarticle',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
