# Generated by Django 3.2.13 on 2022-05-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20220522_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainarticle',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
