# Generated by Django 3.2.13 on 2022-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='in_mailing',
            field=models.BooleanField(default=False),
        ),
    ]
