# Generated by Django 3.2.13 on 2022-05-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_in_mailing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='in_mailing',
            new_name='in_mailing_list',
        ),
    ]
